version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: emergency_news_redis
    ports:
      - "6380:6379"   # host port 6380 -> container port 6379
    networks:
      - backend_network

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emergency_news_app
    command: >
      sh -c "python manage.py migrate --noinput &&
             gunicorn emergency_news.wsgi:application --bind 0.0.0.0:9000"
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0   # internal Docker connection stays the same
    networks:
      - backend_network

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emergency_news_celery_worker
    command: >
      sh -c "python manage.py migrate --noinput &&
             celery -A emergency_news worker -l info"
    volumes:
      - .:/app
    depends_on:
      - django
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
    networks:
      - backend_network

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emergency_news_celery_beat
    command: >
      sh -c "python manage.py migrate --noinput &&
             celery -A emergency_news beat -l info"
    volumes:
      - .:/app
    depends_on:
      - django
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
